/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author camil
 */
public class Servicios_frame extends javax.swing.JFrame {

    /**
     * Creates new form Servicios_frame
     */
    public Servicios_frame() {
        initComponents();
        setTitle("Servicios");
        setResizable(false);
        setLocationRelativeTo(this);
        setSize(601, 557);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtLinea = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        btnAceptarPeticion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtAgnio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        comboBoxTipo = new javax.swing.JComboBox<>();
        comboBox_servicio = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Servicios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 40, 98, 40);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("Línea:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 240, 66, 24);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Agregar información del auto:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(57, 141, 193, 24);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Marca:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(64, 185, 66, 24);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setText("Tipo:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 390, 66, 24);

        txtLinea.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLineaActionPerformed(evt);
            }
        });
        getContentPane().add(txtLinea);
        txtLinea.setBounds(150, 240, 108, 30);

        txtMarca.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(150, 180, 108, 30);

        btnAceptarPeticion.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        btnAceptarPeticion.setText("Aceptar");
        btnAceptarPeticion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPeticionActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptarPeticion);
        btnAceptarPeticion.setBounds(310, 390, 140, 32);

        jLabel6.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel6.setText("Año;");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 290, 66, 24);

        txtAgnio.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtAgnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgnioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAgnio);
        txtAgnio.setBounds(150, 290, 108, 30);

        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel7.setText("Codigo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 340, 66, 24);

        txtCodigo.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(150, 340, 108, 30);

        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Auto", "Camioneta" }));
        getContentPane().add(comboBoxTipo);
        comboBoxTipo.setBounds(150, 390, 110, 26);

        comboBox_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lavado básico", "Lavado especial", "Desinfección básica", "Desinfección avanzada", "Combo 1", "Combo 2", "Combo 3" }));
        getContentPane().add(comboBox_servicio);
        comboBox_servicio.setBounds(310, 180, 190, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLineaActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtAgnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgnioActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void btnAceptarPeticionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPeticionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAceptarPeticionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicios_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicios_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptarPeticion;
    public javax.swing.JComboBox<String> comboBoxTipo;
    public javax.swing.JComboBox<String> comboBox_servicio;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txtAgnio;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtLinea;
    public javax.swing.JTextField txtMarca;
    // End of variables declaration//GEN-END:variables
}
