/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames_utilidad;

import centrodeatención.Centro;
import centrodeatención.Medicos;
import frames.Medicos_frame;
import frames.Pacientes_frame;
import frames.frame_principal;
import java.util.ArrayList;

/**
 *
 * @author camil
 */
public class Seleccionar_centros extends javax.swing.JFrame {

    /**
     * Creates new form Seleccionar_centros
     */
    public ArrayList<Centro> lista_centros_seleccionar = new ArrayList();
    frame_principal frame_principal;
    Medicos_frame medicos_frame;
    String centro_aux;
    public Seleccionar_centros(frame_principal frame_principal, Medicos_frame medicos_frame) {
        initComponents();
        setSize(500, 450);
        setResizable(false);
        lista_centros_seleccionar = frame_principal.lista_centros;
        mostrarTabla();
        this.frame_principal = frame_principal;
        this.medicos_frame = medicos_frame;
        this.centro_aux = medicos_frame.centro_aux;
    }

    private Seleccionar_centros() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        input_seleccionar_medico = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado_centros_disponibles = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 390, 110, 23);
        getContentPane().add(input_seleccionar_medico);
        input_seleccionar_medico.setBounds(330, 360, 80, 20);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Introduzca el código del médico a seleccionar: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 360, 310, 30);

        listado_centros_disponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "Centro médico"
            }
        ));
        jScrollPane1.setViewportView(listado_centros_disponibles);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 452, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i=0;i<lista_centros_seleccionar.size();i++){
            if(Integer.parseInt(input_seleccionar_medico.getText()) == lista_centros_seleccionar.get(i).getCodigoInt()){
                try{
                    if(!"".equals(input_seleccionar_medico.getText())){
                        centro_aux = lista_centros_seleccionar.get(i).getNombre() + " (" + lista_centros_seleccionar.get(i).getCodigoString() + ")";
                    }
                    medicos_frame.actualizarLabelCentro(centro_aux);
                    this.dispose();
                }

                catch(Exception e){}
            }else{
                this.dispose();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
     
    public void mostrarTabla(){
        String matriz[][] = new String[lista_centros_seleccionar.size()][10];
        for(int i=0; i<lista_centros_seleccionar.size();i++){
            matriz[i][0]=lista_centros_seleccionar.get(i).getCodigoString();
            matriz[i][1]=lista_centros_seleccionar.get(i).getNombre();
            matriz[i][2]=lista_centros_seleccionar.get(i).getDireccion();
            
        }
        listado_centros_disponibles.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Código", "Nombres", "Dirección"
            } 
            
        ){
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
            
        });
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_centros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_centros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_centros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_centros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccionar_centros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_seleccionar_medico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_centros_disponibles;
    // End of variables declaration//GEN-END:variables
}
