/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames_utilidad;

import centrodeatención.Medicos;
import centrodeatención.Pacientes;
import frames.Pacientes_frame;
import frames.frame_principal;
import java.util.ArrayList;

/**
 *
 * @author camil
 */
public class Seleccionar_medicos extends javax.swing.JFrame {

    /**
     * Creates new form Seleccionar_medicos
     */
    public ArrayList<Medicos> lista_medicos_seleccionar = new ArrayList();
    frame_principal frame_principal;
    Pacientes_frame pacientes_frame;
    String medico_aux, centro_aux;
    public Seleccionar_medicos() {
    }

    public Seleccionar_medicos(frame_principal frame_principal, Pacientes_frame pacientes_frame) {
        initComponents();
        setSize(500, 500);
        setResizable(false);
        lista_medicos_seleccionar = frame_principal.lista_medicos;
        mostrarTabla();
        this.frame_principal = frame_principal;
        this.pacientes_frame = pacientes_frame;
        this.medico_aux = pacientes_frame.medico_aux;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listado_medicos_disponibles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        input_seleccionar_medico = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        listado_medicos_disponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "Centro médico"
            }
        ));
        jScrollPane1.setViewportView(listado_medicos_disponibles);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 30, 452, 310);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel1.setText("Introduzca el código del médico a seleccionar: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 360, 310, 30);
        getContentPane().add(input_seleccionar_medico);
        input_seleccionar_medico.setBounds(330, 360, 80, 20);

        jButton1.setText("Seleccionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 390, 110, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i=0;i<lista_medicos_seleccionar.size();i++){
            if(Integer.parseInt(input_seleccionar_medico.getText()) == lista_medicos_seleccionar.get(i).getCodigoInt()){
                try{
                    if(!"".equals(input_seleccionar_medico.getText())){
                        medico_aux = lista_medicos_seleccionar.get(i).getNombres() + " " + lista_medicos_seleccionar.get(i).getApellidos() + " (" + lista_medicos_seleccionar.get(i).getCodigoString() + ")";
                        centro_aux = lista_medicos_seleccionar.get(i).getCentro();
                    }
                     pacientes_frame.actualizarLabel(medico_aux);
                     pacientes_frame.actualizarLabelCentro(centro_aux);
                    this.dispose();
                }

                catch(Exception e){}
            }else{
                this.dispose();
            }
        }      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void mostrarTabla(){
        String matriz[][] = new String[lista_medicos_seleccionar.size()][10];
        for(int i=0; i<lista_medicos_seleccionar.size();i++){
            matriz[i][0]=lista_medicos_seleccionar.get(i).getCodigoString();
            matriz[i][1]=lista_medicos_seleccionar.get(i).getNombres();
            matriz[i][2]=lista_medicos_seleccionar.get(i).getApellidos();
            matriz[i][3]=lista_medicos_seleccionar.get(i).getSexo();
            matriz[i][4]=lista_medicos_seleccionar.get(i).getCentro();
        }
        listado_medicos_disponibles.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Código", "Nombres", "Apellidos", "Sexo", "centro Médico"
            } 
            
        ){
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
            
        });
 
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seleccionar_medicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seleccionar_medicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField input_seleccionar_medico;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_medicos_disponibles;
    // End of variables declaration//GEN-END:variables
}
