/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import centrodeatención.Medicos;
import centrodeatención.Pacientes;
import frames_utilidad.Seleccionar_centros;
import java.util.ArrayList;

/**
 *
 * @author camil
 */
public class Medicos_frame extends javax.swing.JFrame {

    /**
     * Creates new form Medicos_frame
     */
    public ArrayList<Medicos> lista_medicos1 = new ArrayList();
    public String centro_aux;
    frame_principal frame_principal;
    public Medicos_frame(frame_principal frame_principal) {
        initComponents();
        setSize(793, 768);
        setTitle("Pacientes");
        setResizable(false);
        this.frame_principal = frame_principal;
        setLocationRelativeTo(null);
        lista_medicos1 = frame_principal.lista_medicos;
        frame_interno_agregar_medico.setVisible(false);
        mostrarTabla();

    }

    private Medicos_frame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listado_pacientes = new javax.swing.JTable();
        btn_agregar_paciente = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_panel_actualizar = new javax.swing.JButton();
        panel_borrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_borrar = new javax.swing.JButton();
        input_borrar_codigo = new javax.swing.JTextField();
        panel_actualizar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_actualizar = new javax.swing.JButton();
        input_actualizar = new javax.swing.JTextField();
        frame_interno_agregar_medico = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        input_sexo = new javax.swing.JTextField();
        btn_enviar = new javax.swing.JButton();
        input_nombres = new javax.swing.JTextField();
        input_codigo = new javax.swing.JTextField();
        input_apellidos = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        input_residencia = new javax.swing.JTextField();
        btn_enviar_actualizar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        input_centro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic", 0, 24)); // NOI18N
        jLabel1.setText("Listado de Médico");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 40, 340, 40);

        listado_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Sexo", "Nombres", "Apellidos", "Dirección", "Centro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listado_pacientes.setColumnSelectionAllowed(true);
        listado_pacientes.setRowHeight(20);
        jScrollPane1.setViewportView(listado_pacientes);
        listado_pacientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 90, 750, 270);

        btn_agregar_paciente.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btn_agregar_paciente.setText("Agregar médico");
        btn_agregar_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_pacienteActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar_paciente);
        btn_agregar_paciente.setBounds(20, 380, 180, 37);

        btn_eliminar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btn_eliminar.setText("Eliminar médico");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar);
        btn_eliminar.setBounds(210, 380, 200, 37);

        btn_panel_actualizar.setFont(new java.awt.Font("Yu Gothic", 0, 18)); // NOI18N
        btn_panel_actualizar.setText("Actualizar médico");
        btn_panel_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_panel_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_panel_actualizar);
        btn_panel_actualizar.setBounds(420, 380, 240, 37);

        panel_borrar.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel4.setText("Digite el código del médico");
        panel_borrar.add(jLabel4);
        jLabel4.setBounds(10, 10, 200, 20);

        jLabel5.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel5.setText("a eliminar:");
        panel_borrar.add(jLabel5);
        jLabel5.setBounds(10, 30, 80, 24);

        btn_borrar.setText("Borrar");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        panel_borrar.add(btn_borrar);
        btn_borrar.setBounds(120, 30, 80, 23);
        panel_borrar.add(input_borrar_codigo);
        input_borrar_codigo.setBounds(80, 30, 30, 20);

        getContentPane().add(panel_borrar);
        panel_borrar.setBounds(210, 420, 200, 60);

        panel_actualizar.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setText("Digite el código del médico");
        panel_actualizar.add(jLabel3);
        jLabel3.setBounds(10, 10, 200, 20);

        jLabel2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel2.setText("a actualizar:");
        panel_actualizar.add(jLabel2);
        jLabel2.setBounds(10, 30, 80, 24);

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        panel_actualizar.add(btn_actualizar);
        btn_actualizar.setBounds(140, 30, 100, 20);
        panel_actualizar.add(input_actualizar);
        input_actualizar.setBounds(100, 30, 30, 20);

        getContentPane().add(panel_actualizar);
        panel_actualizar.setBounds(420, 420, 240, 50);

        frame_interno_agregar_medico.setBackground(new java.awt.Color(204, 204, 204));
        frame_interno_agregar_medico.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel13.setText("Nombres:");
        frame_interno_agregar_medico.add(jLabel13);
        jLabel13.setBounds(20, 70, 80, 20);

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel14.setText("Apellidos:");
        frame_interno_agregar_medico.add(jLabel14);
        jLabel14.setBounds(20, 109, 64, 20);

        jLabel15.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel15.setText("Código:");
        frame_interno_agregar_medico.add(jLabel15);
        jLabel15.setBounds(20, 30, 50, 20);

        jLabel16.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel16.setText("Sexo:");
        frame_interno_agregar_medico.add(jLabel16);
        jLabel16.setBounds(20, 149, 64, 20);

        input_sexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_sexoActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(input_sexo);
        input_sexo.setBounds(60, 149, 100, 20);

        btn_enviar.setText("Agregar médico");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(btn_enviar);
        btn_enviar.setBounds(578, 150, 160, 23);

        input_nombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nombresActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(input_nombres);
        input_nombres.setBounds(90, 70, 170, 20);

        input_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_codigoActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(input_codigo);
        input_codigo.setBounds(80, 30, 100, 20);

        input_apellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_apellidosActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(input_apellidos);
        input_apellidos.setBounds(90, 110, 170, 20);

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel20.setText("Centro:");
        frame_interno_agregar_medico.add(jLabel20);
        jLabel20.setBounds(298, 73, 62, 20);

        input_residencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_residenciaActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(input_residencia);
        input_residencia.setBounds(470, 30, 170, 20);

        btn_enviar_actualizar.setText("Actualizar médico");
        btn_enviar_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviar_actualizarActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(btn_enviar_actualizar);
        btn_enviar_actualizar.setBounds(578, 109, 160, 23);

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel21.setText("Dirección de residencia:");
        frame_interno_agregar_medico.add(jLabel21);
        jLabel21.setBounds(300, 40, 160, 20);
        frame_interno_agregar_medico.add(jLabel6);
        jLabel6.setBounds(366, 73, 109, 0);

        jButton1.setText("Seleccionar centro");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        frame_interno_agregar_medico.add(jButton1);
        jButton1.setBounds(480, 70, 140, 23);
        frame_interno_agregar_medico.add(input_centro);
        input_centro.setBounds(350, 70, 120, 20);

        getContentPane().add(frame_interno_agregar_medico);
        frame_interno_agregar_medico.setBounds(20, 480, 750, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregar_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_pacienteActionPerformed
        input_nombres.setText("");
        input_apellidos.setText("");
        input_codigo.setText("");
        input_sexo.setText("");
        input_residencia.setText("");
        input_actualizar.setText("");
        frame_interno_agregar_medico.setVisible(true);
        panel_borrar.setVisible(false);
        btn_enviar_actualizar.setVisible(false);
        panel_actualizar.setVisible(false);
        btn_enviar.setVisible(true);
    }//GEN-LAST:event_btn_agregar_pacienteActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        frame_interno_agregar_medico.setVisible(false);
        panel_borrar.setVisible(true);
        panel_actualizar.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_panel_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_panel_actualizarActionPerformed
        for(int i=0;i<lista_medicos1.size();i++){
            if(lista_medicos1.isEmpty() == false){
                try{
                    panel_actualizar.setVisible(true);

                }catch(Exception e){}
                System.out.println("No hay pacientes.");

            }
        }
    }//GEN-LAST:event_btn_panel_actualizarActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        for(int i=0;i<lista_medicos1.size();i++){
            if(input_borrar_codigo.getText().equals(lista_medicos1.get(i).getCodigoString())){
                lista_medicos1.remove(i);
            }
        }
        input_borrar_codigo.setText("");
        panel_borrar.setVisible(false);
        mostrarTabla();        // TODO add your handling code here:        // TODO add your handling code here:
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        for(int i=0;i<lista_medicos1.size();i++){
            if(Integer.parseInt(input_actualizar.getText()) == lista_medicos1.get(i).getCodigoInt()){
                panel_borrar.setVisible(false);
                input_codigo.setText(lista_medicos1.get(i).getCodigoString());
                input_nombres.setText(lista_medicos1.get(i).getNombres());
                input_apellidos.setText(lista_medicos1.get(i).getApellidos());
                input_residencia.setText(lista_medicos1.get(i).getDireccion_residencia());
                input_sexo.setText(lista_medicos1.get(i).getSexo());

                frame_interno_agregar_medico.setVisible(true);
                btn_enviar.setVisible(false);
                btn_enviar_actualizar.setVisible(true);
            }
        }

    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_enviar_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviar_actualizarActionPerformed
        for(int i=0;i<lista_medicos1.size();i++){
            if(input_codigo.getText().equals(lista_medicos1.get(i).getCodigoString())){
                try{
                    String nombres, apellidos, sexo, residencia, centro, motivo, medico, fecha;
                    int codigo;
                    nombres = input_nombres.getText();
                    apellidos = input_apellidos.getText();
                    sexo = input_sexo.getText();
                    residencia = input_residencia.getText();

                    if(!"".equals(nombres)&&!"".equals(apellidos)&&!"".equals(sexo)&&!"".equals(residencia)){
                        lista_medicos1.get(i).setNombres(nombres);
                        lista_medicos1.get(i).setApellidos(apellidos);
                        lista_medicos1.get(i).setSexo(sexo);
                        lista_medicos1.get(i).setDireccion_residencia(residencia);
                    }

                }catch(Exception e){}

            }
        }
        frame_interno_agregar_medico.setVisible(false);
        mostrarTabla();
        input_nombres.setText("");
        input_apellidos.setText("");
        input_codigo.setText("");
        input_sexo.setText("");
        input_residencia.setText("");
        input_actualizar.setText("");
        panel_actualizar.setVisible(false);
    }//GEN-LAST:event_btn_enviar_actualizarActionPerformed

    private void input_residenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_residenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_residenciaActionPerformed

    private void input_apellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_apellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_apellidosActionPerformed

    private void input_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_codigoActionPerformed

    private void input_nombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nombresActionPerformed

    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        try{
            String nombres, apellidos, sexo, residencia, centro;
            int codigo;
            nombres = input_nombres.getText();
            apellidos = input_apellidos.getText();
            codigo = Integer.parseInt(input_codigo.getText());
            sexo = input_sexo.getText();
            residencia = input_residencia.getText();
            centro = input_centro.getText();

            if(!"".equals(nombres)&&!"".equals(apellidos)&&!"".equals(codigo)&&!"".equals(sexo)&&!"".equals(residencia)){
                Medicos medico_aux = new Medicos();
                medico_aux.setNombres(nombres);
                medico_aux.setApellidos(apellidos);
                medico_aux.setCodigo(codigo);
                medico_aux.setSexo(sexo);
                medico_aux.setDireccion_residencia(residencia);
                medico_aux.setCentro(centro);
                lista_medicos1.add(medico_aux);
            }

        }catch(Exception e){}
        mostrarTabla();
        frame_interno_agregar_medico.setVisible(false);
        input_nombres.setText("");
        input_apellidos.setText("");
        input_codigo.setText("");
        input_sexo.setText("");
        input_residencia.setText("");
    }//GEN-LAST:event_btn_enviarActionPerformed

    private void input_sexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_sexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_sexoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Seleccionar_centros seleccionar_centros = new Seleccionar_centros(frame_principal, this);
        seleccionar_centros.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicos_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicos_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicos_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicos_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicos_frame().setVisible(true);
            }
        });
    }
    public void mostrarTabla(){
        String matriz[][] = new String[lista_medicos1.size()][10];
        for(int i=0; i<lista_medicos1.size();i++){
            matriz[i][0]=lista_medicos1.get(i).getCodigoString();
            matriz[i][1]=lista_medicos1.get(i).getNombres();
            matriz[i][2]=lista_medicos1.get(i).getApellidos();
            matriz[i][3]=lista_medicos1.get(i).getSexo();
            matriz[i][4]=lista_medicos1.get(i).getDireccion_residencia();
            matriz[i][5]=lista_medicos1.get(i).getCentro();

        }
        listado_pacientes.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "Código", "Nombres", "Apellidos", "Sexo", "Dirección", "Centro"
            } 
            
        ){
            
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            };
            
        });
 
    }
    public void actualizarLabelCentro(String centro_aux){
        this.centro_aux = centro_aux;
        input_centro.setText(centro_aux);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_agregar_paciente;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_enviar;
    private javax.swing.JButton btn_enviar_actualizar;
    private javax.swing.JButton btn_panel_actualizar;
    private javax.swing.JPanel frame_interno_agregar_medico;
    private javax.swing.JTextField input_actualizar;
    private javax.swing.JTextField input_apellidos;
    private javax.swing.JTextField input_borrar_codigo;
    private javax.swing.JLabel input_centro;
    private javax.swing.JTextField input_codigo;
    private javax.swing.JTextField input_nombres;
    private javax.swing.JTextField input_residencia;
    private javax.swing.JTextField input_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listado_pacientes;
    private javax.swing.JPanel panel_actualizar;
    private javax.swing.JPanel panel_borrar;
    // End of variables declaration//GEN-END:variables
}
